---
- name: Copying ansible configuration
  copy:
    src: files/.ansible.cfg
    dest: /home/vagrant/.ansible.cfg
- name: Injecting ansible inventory file for installing OpenShift
  become: true
  template:
    src: files/inventory
    dest: /etc/ansible/hosts
