---
- hosts: all
  vars:
    ansible_env:
      ANSIBLE_HOST_KEY_CHECKING: False
  tasks:
    - include_tasks: update.yml
    - include_tasks: originrepo.yml
    - include_tasks: prerequisites.yml
    - include_tasks: sshkeys.yml
    - include_tasks: configureinventory.yml
    - include_tasks: installorigin.yml
    - include_tasks: createusers.yml
    - include_tasks: printdetails.yml
